- generic [ref=e2]:
  - generic [ref=e3]:
    - generic [ref=e4]:
      - link [ref=e5] [cursor=pointer]:
        - /url: /recent
        - img [ref=e6]
      - link "Pinboard" [ref=e7] [cursor=pointer]:
        - /url: /
      - generic [ref=e8]:
        - text: (
        - link "oumu" [ref=e9] [cursor=pointer]:
          - /url: /u:oumu
        - text: )
    - generic [ref=e11]:
      - link "sieć" [ref=e12] [cursor=pointer]:
        - /url: /network/
      - text: ‧
      - link "notki" [ref=e13] [cursor=pointer]:
        - /url: /notes/
      - text: ‧
      - link "popularne" [ref=e14] [cursor=pointer]:
        - /url: /popular/
      - text: ‧
      - link "dodaj URL" [ref=e15] [cursor=pointer]:
        - /url: /add/?next=https%3A%2F%2Fpinboard.in%2Fu%3Aoumu
      - text: ‧
      - link "dodaj notkę" [ref=e16] [cursor=pointer]:
        - /url: /note/add/
      - text: ‧
      - link "ustawienia" [ref=e17] [cursor=pointer]:
        - /url: /settings/
      - text: ‧
      - link "konto" [ref=e18] [cursor=pointer]:
        - /url: /u:oumu/profile/
      - link "wyloguj" [ref=e19] [cursor=pointer]:
        - /url: /logout/
  - generic [ref=e21]:
    - generic [ref=e22]:
      - link "ustawienia" [ref=e24] [cursor=pointer]:
        - /url: /settings/settings
      - link "prywatność" [ref=e26] [cursor=pointer]:
        - /url: /settings/privacy
      - link "hasło" [ref=e28] [cursor=pointer]:
        - /url: /settings/password
      - link "importowanie" [ref=e30] [cursor=pointer]:
        - /url: /settings/import
      - link "archiwum" [ref=e32] [cursor=pointer]:
        - /url: /settings/backup
    - generic [ref=e35]:
      - button "Zachować zmiany" [ref=e36]
      - table [ref=e37]:
        - rowgroup [ref=e38]:
          - row [ref=e39]:
            - cell [ref=e40]
            - cell [ref=e41]
          - 'row "Język: Polski" [ref=e42]':
            - cell "Język:" [ref=e43]
            - cell "Polski" [ref=e44]:
              - combobox [ref=e45]:
                - option "English"
                - option "日本語"
                - option "Polski" [selected]
                - option "Deutsch"
                - option "Français"
                - option "中文"
                - option "Русский"
          - 'row "Strefa czasowa: +8:00 : Pekin, Hongkong" [ref=e46]':
            - cell "Strefa czasowa:" [ref=e47]
            - 'cell "+8:00 : Pekin, Hongkong" [ref=e48]':
              - combobox [ref=e49]:
                - option "UTC (domyślny)"
                - 'option "-9:00 : Alaska"'
                - 'option "-8:00 : Tijuana, Baja California"'
                - 'option "-8:00 : Zachodnie wybrzeże USA"'
                - 'option "-7:00 : Czas górny"'
                - 'option "-7:00 : Chihuahua, La Paz"'
                - 'option "-7:00 : Arizona"'
                - 'option "-6:00 : Ameryka Centralna"'
                - 'option "-6:00 : Guadalajara, Meksyk"'
                - 'option "-6:00 : Czas centralny"'
                - 'option "-5:00 : Czas wschodni"'
                - 'option "-5:00 : Kuba"'
                - 'option "-5:00 : Bogota, Lima, Quito"'
                - 'option "-4:30 : Caracas"'
                - 'option "-4:00 : Santiago"'
                - 'option "-4:00 : La Paz"'
                - 'option "-4:00 : Brazylia"'
                - 'option "-4:00 : Czas atlantycki"'
                - 'option "-3:30 : Nowa Fundlandia"'
                - 'option "-3:00 : Montevideo"'
                - 'option "-3:00 : Buenos Aires"'
                - 'option "-3:00 : Brazylia"'
                - 'option "+0:00 : Londyn, Reykjavík, UTC"'
                - 'option "+1:00 : Amsterdam, Berlin, Rzym"'
                - 'option "+1:00 : Belgrad, Budapeszt, Praga"'
                - 'option "+2:00 : Bejrut"'
                - 'option "+2:00 : Kair"'
                - 'option "+2:00 : Harare, Pretoria"'
                - 'option "+2:00 : Jerozolima"'
                - 'option "+3:00 : Nairobi"'
                - 'option "+3:30 : Teheran"'
                - 'option "+4:00 : Moskwa, Petersburg"'
                - 'option "+4:00 : Abu Zabi, Maskat"'
                - 'option "+4:00 : Erywań"'
                - 'option "+4:30 : Kabul"'
                - 'option "+5:00 : Jekaterynburg"'
                - 'option "+5:00 : Taszkent"'
                - 'option "+5:30 : Indie"'
                - 'option "+5:45 : Nepal"'
                - 'option "+6:00 : Astana, Dhaka"'
                - 'option "+6:00 : Nowosybirsk"'
                - 'option "+6:30 : Birma"'
                - 'option "+7:00 : Bangkok, Hanoi, Jakarta"'
                - 'option "+7:00 : Krasnojarsk"'
                - 'option "+8:00 : Pekin, Hongkong" [selected]'
                - 'option "+8:00 : Irkuck, Ułan Bator"'
                - 'option "+8:00 : Perth"'
                - 'option "+9:00 : Osaka, Sapporo, Tokio"'
                - 'option "+9:00 : Seul"'
                - 'option "+9:30 : Adelajda"'
                - 'option "+9:30 : Darwin"'
                - 'option "+10:00 : Brisbane"'
                - 'option "+10:00 : Hobart"'
                - 'option "+10:00 : Władywostok"'
                - 'option "+11:00 : Magadan"'
                - 'option "+12:00 : Auckland, Wellington"'
                - 'option "+12:00 : Fidżi, Kamczatka"'
                - 'option "-11:00 : Midway, Samoa"'
                - 'option "-10:00 : Aleuty, Hawaje"'
          - row "Ustawienia Ogólne" [ref=e50]:
            - cell "Ustawienia Ogólne" [ref=e51]:
              - heading "Ustawienia Ogólne" [level=2] [ref=e52]
          - row "automatyczne uzupełnianie tagów ?" [ref=e53]:
            - cell [ref=e54]:
              - checkbox [checked] [ref=e55]
            - cell "automatyczne uzupełnianie tagów ?" [ref=e56]:
              - text: automatyczne uzupełnianie tagów
              - link "?" [ref=e57] [cursor=pointer]:
                - /url: "#"
          - row "pokazywać tagi w porządku alfabetycznym w menu rozwijalnym ?" [ref=e58]:
            - cell [ref=e59]:
              - checkbox [checked] [ref=e60]
            - cell "pokazywać tagi w porządku alfabetycznym w menu rozwijalnym ?" [ref=e61]:
              - text: pokazywać tagi w porządku alfabetycznym w menu rozwijalnym
              - link "?" [ref=e62] [cursor=pointer]:
                - /url: "#"
          - row "klawisz \"enter\" wybiera taga z menu rozwijalnego ?" [ref=e63]:
            - cell [ref=e64]:
              - checkbox [ref=e65]
            - cell "klawisz \"enter\" wybiera taga z menu rozwijalnego ?" [ref=e66]:
              - text: klawisz "enter" wybiera taga z menu rozwijalnego
              - link "?" [ref=e67] [cursor=pointer]:
                - /url: "#"
          - row "kliknięcie na link oznacza, że został przeczytany ?" [ref=e68]:
            - cell [ref=e69]:
              - checkbox [ref=e70]
            - cell "kliknięcie na link oznacza, że został przeczytany ?" [ref=e71]:
              - text: kliknięcie na link oznacza, że został przeczytany
              - link "?" [ref=e72] [cursor=pointer]:
                - /url: "#"
          - row "Otwierać linki w nowym okienku ?" [ref=e73]:
            - cell [ref=e74]:
              - checkbox [ref=e75]
            - cell "Otwierać linki w nowym okienku ?" [ref=e76]:
              - text: Otwierać linki w nowym okienku
              - link "?" [ref=e77] [cursor=pointer]:
                - /url: "#"
          - row "uruchomić skróty klawiszowe ?" [ref=e78]:
            - cell [ref=e79]:
              - checkbox [ref=e80]
            - cell "uruchomić skróty klawiszowe ?" [ref=e81]:
              - text: uruchomić skróty klawiszowe
              - link "?" [ref=e82] [cursor=pointer]:
                - /url: "#"
          - row "subskrybowanie tagów ?" [ref=e83]:
            - cell [ref=e84]:
              - checkbox [checked] [ref=e85]
            - cell "subskrybowanie tagów ?" [ref=e86]:
              - text: subskrybowanie tagów
              - link "?" [ref=e87] [cursor=pointer]:
                - /url: "#"
          - row "jestem fanem! ?" [ref=e88]:
            - cell [ref=e89]:
              - checkbox [ref=e90]
            - cell "jestem fanem! ?" [ref=e91]:
              - text: jestem fanem!
              - link "?" [ref=e92] [cursor=pointer]:
                - /url: "#"
          - row "uruchomić wiązki tagów ?" [ref=e93]:
            - cell [ref=e94]:
              - checkbox [checked] [ref=e95]
            - cell "uruchomić wiązki tagów ?" [ref=e96]:
              - text: uruchomić wiązki tagów
              - link "?" [ref=e97] [cursor=pointer]:
                - /url: "#"
          - row [ref=e98]:
            - cell [ref=e99]
            - cell [ref=e100]
          - row "Wygląd Zakładek" [ref=e101]:
            - cell "Wygląd Zakładek" [ref=e102]:
              - heading "Wygląd Zakładek" [level=2] [ref=e103]
          - row "pokazywać tagi w porządku alfabetycznym ?" [ref=e104]:
            - cell [ref=e105]:
              - checkbox [ref=e106]
            - cell "pokazywać tagi w porządku alfabetycznym ?" [ref=e107]:
              - text: pokazywać tagi w porządku alfabetycznym
              - link "?" [ref=e108] [cursor=pointer]:
                - /url: "#"
          - row "pokayzwać pełny URL pod tytułem zakładki ?" [ref=e109]:
            - cell [ref=e110]:
              - checkbox [checked] [ref=e111]
            - cell "pokayzwać pełny URL pod tytułem zakładki ?" [ref=e112]:
              - text: pokayzwać pełny URL pod tytułem zakładki
              - link "?" [ref=e113] [cursor=pointer]:
                - /url: "#"
          - row "pozwolić innym widzieć, że mam ich w sieci znajomych ?" [ref=e114]:
            - cell [ref=e115]:
              - checkbox [checked] [ref=e116]
            - cell "pozwolić innym widzieć, że mam ich w sieci znajomych ?" [ref=e117]:
              - text: pozwolić innym widzieć, że mam ich w sieci znajomych
              - link "?" [ref=e118] [cursor=pointer]:
                - /url: "#"
          - row "Pokazywać dokładne daty stworzenia ?" [ref=e119]:
            - cell [ref=e120]:
              - checkbox [checked] [ref=e121]
            - cell "Pokazywać dokładne daty stworzenia ?" [ref=e122]:
              - text: Pokazywać dokładne daty stworzenia
              - link "?" [ref=e123] [cursor=pointer]:
                - /url: "#"
          - row [ref=e124]:
            - cell [ref=e125]
            - cell [ref=e126]
          - row "Instapaper" [ref=e127]:
            - cell "Instapaper" [ref=e128]:
              - heading "Instapaper" [level=2] [ref=e129]
          - 'row "URL feeda Instapaper: http://www.instapaper.com/rss/1017398/4wEPY3B0p75ttxuZVXRjbziwR4" [ref=e130]':
            - 'cell "URL feeda Instapaper: http://www.instapaper.com/rss/1017398/4wEPY3B0p75ttxuZVXRjbziwR4" [ref=e131]':
              - text: "URL feeda Instapaper:"
              - textbox [ref=e132]: http://www.instapaper.com/rss/1017398/4wEPY3B0p75ttxuZVXRjbziwR4
          - row "dodawać zakładki z konta Instapaper ?" [ref=e133]:
            - cell [ref=e134]:
              - checkbox [ref=e135]
            - cell "dodawać zakładki z konta Instapaper ?" [ref=e136]:
              - text: dodawać zakładki z konta Instapaper
              - link "?" [ref=e137] [cursor=pointer]:
                - /url: "#"
          - row "traktować jako przeczytane do czytania" [ref=e138]:
            - cell [ref=e139]
            - cell "traktować jako przeczytane do czytania" [ref=e140]:
              - text: traktować jako
              - radio "przeczytane" [checked] [ref=e141]
              - text: przeczytane
              - radio "do czytania" [ref=e142]
              - text: do czytania
          - row "Pocket" [ref=e143]:
            - cell "Pocket" [ref=e144]:
              - heading "Pocket" [level=2] [ref=e145]
          - 'row "Imię użytkownika Pocket: oumu" [ref=e146]':
            - 'cell "Imię użytkownika Pocket: oumu" [ref=e147]':
              - text: "Imię użytkownika Pocket:"
              - textbox [ref=e148]: oumu
          - row "dodawać zakładki z konta Pocket ?" [ref=e149]:
            - cell [ref=e150]:
              - checkbox [ref=e151]
            - cell "dodawać zakładki z konta Pocket ?" [ref=e152]:
              - text: dodawać zakładki z konta Pocket
              - link "?" [ref=e153] [cursor=pointer]:
                - /url: "#"
          - row "traktować jako przeczytane do czytania" [ref=e154]:
            - cell [ref=e155]
            - cell "traktować jako przeczytane do czytania" [ref=e156]:
              - text: traktować jako
              - radio "przeczytane" [checked] [ref=e157]
              - text: przeczytane
              - radio "do czytania" [ref=e158]
              - text: do czytania
          - row "Adres e-mail" [ref=e159]:
            - cell "Adres e-mail" [ref=e160]:
              - heading "Adres e-mail" [level=2] [ref=e161]
          - row "dodawaj załadki przysłane pocztą elektroniczną ? post+oumu+fb73af@pinboard.in (instrukcje)" [ref=e162]:
            - cell [ref=e163]:
              - checkbox [checked] [ref=e164]
            - cell "dodawaj załadki przysłane pocztą elektroniczną ? post+oumu+fb73af@pinboard.in (instrukcje)" [ref=e165]:
              - text: dodawaj załadki przysłane pocztą elektroniczną
              - link "?" [ref=e166] [cursor=pointer]:
                - /url: "#"
              - paragraph [ref=e167]:
                - text: post+oumu+fb73af@pinboard.in (
                - link "instrukcje" [ref=e168] [cursor=pointer]:
                  - /url: /howto/#post_by_mail
                - text: )
      - button "Zachować zmiany" [ref=e169]
  - generic [ref=e170]:
    - text: © Nine Fives Software. Pytania? Problemy? Napisz do nas! <
    - link "support@pinboard.in" [ref=e171] [cursor=pointer]:
      - /url: mailto:support@pinboard.in
    - text: ">"
    - separator [ref=e172]
    - link "TOS" [ref=e173] [cursor=pointer]:
      - /url: /tos/
    - text: ‧
    - link "prywatność" [ref=e174] [cursor=pointer]:
      - /url: /privacy/
    - text: ‧
    - link "o nas" [ref=e175] [cursor=pointer]:
      - /url: /about/
    - text: ‧
    - link "blog" [ref=e176] [cursor=pointer]:
      - /url: http://blog.pinboard.in
    - text: ‧
    - link "FAQ" [ref=e177] [cursor=pointer]:
      - /url: /faq/
    - text: ‧
    - link "linki" [ref=e178] [cursor=pointer]:
      - /url: /resources/
    - text: ‧
    - link "bezpieczeństwo" [ref=e179] [cursor=pointer]:
      - /url: /security/